version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: trimminflow-db
    restart: always
    environment:
      POSTGRES_DB: trimminflow
      POSTGRES_USER: trimminflow_user
      POSTGRES_PASSWORD: mx269518
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: trimminflow-backend
    restart: always
    ports:
      - "8080:8080"e
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trimminflow
      SPRING_DATASOURCE_USERNAME: trimminflow_user
      SPRING_DATASOURCE_PASSWORD: mx269518
    depends_on:
      - postgres

volumes:
  postgres_data:
