name: CI
# WHEN to run this workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Start a PostgreSQL database for testing
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: trimminflow
          POSTGRES_USER: trimminflow_user
          POSTGRES_PASSWORD: mx269518
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Setup environment
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      #Build and test
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/trimminflow
        SPRING_DATASOURCE_USERNAME: trimminflow_user
        SPRING_DATASOURCE_PASSWORD: mx269518
      run: cd demo && chmod +x gradlew && ./gradlew build sonar
